// <auto-generated />
using DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(GestorLinkSocialDbContext))]
    [Migration("20240115190140_p")]
    partial class p
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DB.Modelo.Accesos", b =>
                {
                    b.Property<int>("idAcceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idAcceso"));

                    b.Property<int>("codigoAcceso")
                        .HasColumnType("integer");

                    b.Property<string>("descripcionAcceso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idAcceso");

                    b.ToTable("Accesos");
                });

            modelBuilder.Entity("DB.Modelo.Usuarios", b =>
                {
                    b.Property<int>("idUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idUsuario"));

                    b.Property<string>("contraseña")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("correoElectronico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("dniUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("movilUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombreCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("idUsuario");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
